version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    restart: unless-stopped

  weather:
    build:
      context: ./
    ports:
      - "8080:8080"
    container_name: weatherApi
    depends_on:
      - postgres
    restart: unless-stopped
    env_file:
      - .env